services:
  ooni-probe:
    # build: .
    image: altertek/ooni-probe
    container_name: "ooni-probe"
    restart: unless-stopped
    # Overrides the default command and runs the probe every 10 to 12 hours
    command: >
      sh -c "/usr/bin/ooniprobe run unattended --batch
      && /bin/sleep $(shuf -i 36000-42000 -n 1)"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 100m
