name: 'Checks'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

env:
  TEST_TAG: altertek/ooni-probe:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Run hadolint action
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: Dockerfile

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and export to Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}

    - name: Test
      run: |
        docker run --rm ${{ env.TEST_TAG }} /usr/bin/ooniprobe geoip
